### ISSUE TITLE
Add missing information

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/kryptokrona-docs#28]
What is supposted to be listed here: https://docs.kryptokrona.org/about/core-developers ? Just if I should send a PR with supplied information. Also we should probably change this line on this page: https://docs.kryptokrona.org/about/contributors

> Huge thank you to everyone here, they've made major commits to the wiki and helped make it what it is today!

**To:**

> Huge thank you to everyone here, they've made major commits to the project and helped make it what it is today!

**Comment by f-r00t** [comment]
Fixed with [8693185](https://github.com/kryptokrona/kryptokrona-docs/commit/869318505f6c1379517f31d51ff532a07dec6e6c)
